kind: pipeline
type: docker
name: default

workspace:
  base: /src
  path: /

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags:
        - latest
      registry: docker.mbict.nl
      repo: docker.mbict.nl/mbict/mysql-s3-backup
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
        channel: dev
        username: drone
    when:
      status: [ success, failure ]